// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Amount Non-negative amount of treasures/etc.
//
// swagger:model amount
type Amount int64

// Validate validates this amount
func (m Amount) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MinimumInt("", "body", int64(m), 0, false); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this amount based on context it is used
func (m Amount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
