// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson967143c7DecodeGoldenModels(in *jlexer.Lexer, out *License) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "digAllowed":
			if in.IsNull() {
				in.Skip()
				out.DigAllowed = nil
			} else {
				if out.DigAllowed == nil {
					out.DigAllowed = new(Amount)
				}
				*out.DigAllowed = Amount(in.Int64())
			}
		case "digUsed":
			if in.IsNull() {
				in.Skip()
				out.DigUsed = nil
			} else {
				if out.DigUsed == nil {
					out.DigUsed = new(Amount)
				}
				*out.DigUsed = Amount(in.Int64())
			}
		case "id":
			if in.IsNull() {
				in.Skip()
				out.ID = nil
			} else {
				if out.ID == nil {
					out.ID = new(int64)
				}
				*out.ID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson967143c7EncodeGoldenModels(out *jwriter.Writer, in License) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"digAllowed\":"
		out.RawString(prefix[1:])
		if in.DigAllowed == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.DigAllowed))
		}
	}
	{
		const prefix string = ",\"digUsed\":"
		out.RawString(prefix)
		if in.DigUsed == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.DigUsed))
		}
	}
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix)
		if in.ID == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.ID))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v License) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson967143c7EncodeGoldenModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v License) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson967143c7EncodeGoldenModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *License) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson967143c7DecodeGoldenModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *License) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson967143c7DecodeGoldenModels(l, v)
}
